---

- name: Common | Copy k8s.conf to /etc/modules-load.d/
  copy:
    src: modules-load.d_k8s.conf
    dest: /etc/modules-load.d/k8s.conf

- name: Common | Copy k8s.conf to /etc/sysctl.d/
  copy:
    src: sysctl.d_k8s.conf
    dest: /etc/sysctl.d/k8s.conf

