---

- name: Container | Install containerd
  apt:
    pkg:
      - containerd
    update_cache: yes

- name: Container | Enable conatinerd service
  service:
    name: containerd
    enabled: yes

- name: Container | Create containerd directory
  file:
    path: /etc/containerd
    state: directory

- name: Container | Copy containerd config
  copy:
    src: containerd/config.toml
    dest: /etc/containerd/config.toml
  register: containerd_conf

- name: Container | Start containerd service
  service:
    name: containerd.service
    state: restarted
  when: containerd_conf.changed
