---

- name: HAProxy - Keepalived | Install packages
  apt:
    pkg:
      - haproxy
      - keepalived
    update_cache: yes

- name: HAProxy - Keepalived | Copy haproxy.cfg
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  register: haproxy_conf

- name: HAProxy - Keepalived | Start haproxy service
  service:
    name: haproxy.service
    state: restarted
  when: haproxy_conf.changed

- name: HAProxy - Keepalived | Copy keepalived.conf
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  register: keepalived_conf

- name: HAProxy - Keepalived | Start keepalived service
  service:
    name: keepalived.service
    state: restarted
  when: keepalived_conf.changed
