---

- name: Kube - Common | Install common packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes

- name: Kube - Common | Add k8s official GPG key
  shell: curl -fsSL {{ KUBE_GPG_URL_PREFIX }}/{{ CLUSTER_BRANCH }}/deb/Release.key | sudo gpg --dearmor -o {{ KUBE_GPG_PATH }} --yes

- name: Kube - Common | Copy docker.list to /etc/apt/sources.list.d/
  shell: echo 'deb [signed-by={{ KUBE_GPG_PATH }}] {{ KUBE_GPG_URL_PREFIX }}/{{ CLUSTER_BRANCH }}/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: Kube - Common | Install kubeadm, kubelet, kubectl
  apt:
    pkg:
      - kubectl={{ CLUSTER_VERSION }}-1.1
      - kubelet={{ CLUSTER_VERSION }}-1.1
      - kubeadm={{ CLUSTER_VERSION }}-1.1
    update_cache: yes

- name: Kube - Common | Hold kubeadm, kubelet, kubectl version
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubectl
