---

- name: Kube - Control Plane - Init | Check if kube-apiserver.yaml exist
  stat:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
  register: kube_apiserver

- name: Kube - Control Plane - Init | Copy kubeadm-config.yml
  template:
    src: kubeadm-config.yml.j2
    dest: /tmp/kubeadm-config.yml
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Initial K8S cluster
  shell: kubeadm init --config=/tmp/kubeadm-config.yml
  register: kubeadm_init
  retries: 3
  until: kubeadm_init is succeeded or "field is immutable" in kubeadm_init.stderr
  when: not kube_apiserver.stat.exists
  failed_when: kubeadm_init.rc != 0 and "field is immutable" not in kubeadm_init.stderr

- name: Kube - Control Plane - Init | Generate the join command
  shell: kubeadm token create --print-join-command
  register: join_cmd
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Copy the join command to localhost (node)
  local_action: copy content="{{ join_cmd.stdout }}" dest="/tmp/join_cmd" mode=0644
  become: false
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Generate certificate key
  shell: kubeadm init phase upload-certs --upload-certs --skip-headers | grep -v upload-certs
  register: cert_key
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Copy the join command to localhost (control-plane)
  local_action: copy content="{{ join_cmd.stdout }} --control-plane --certificate-key {{ cert_key.stdout }}" dest="/tmp/join_cmd_control_plane" mode=0644
  become: false
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Create .kube directory
  file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Copy config file
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ ansible_user }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: not kube_apiserver.stat.exists

- name: Kube - Control Plane - Init | Check if "~/.kube/config" exist
  stat:
    path: /home/{{ ansible_user }}/.kube/config
  register: kube_config

- name: Kube - Control Plane - Init | Install pod network addon
  shell: kubectl apply -f {{ KUBE_POD_NETWORK }}
  become: false
  when: kube_config.stat.exists
