---

- name: Kube Worker | Check if kubelet.conf exist
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Kube Worker | Set join command as variable
  slurp:
    src: "{{ KUBE_JOIN_CMD_PATH }}"
  register: join_command
  when: not kubelet_conf.stat.exists

- name: debug
  debug:
    msg:
      - "{{ join_command['content'] | b64decode }}"
  when: not kubelet_conf.stat.exists

- name: Kube Worker | Run kubeadm join command
  shell: "{{ join_command['content'] | b64decode }}"
  when: not kubelet_conf.stat.exists

